path_to_data: /Users/nadeaus/Dropbox/aarhus-datathon-genome-study-1-data

countries:
  - Denmark  # Currently only implemented for Denmark
country_codes:
  - DNK

pangolin_lineages:
  - B.1.617.2
  - AY.1
  - AY.10
  - AY.11
  - AY.12
  - AY.2
  - AY.3
  - AY.3.1
  - AY.4
  - AY.5
  - AY.6
  - AY.7
  - AY.8
  - AY.9

min_date: 2021-01-01
max_date: 2021-08-01

subsampling_proportion: 0.05