---
title: "Aarhus Datathon Genome Study 1"
author:
date: 21.08.21
output: html_notebook
---

## Preparation

Load libraries, scripts, and data:

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
source("R/vaccination.R")
source("R/diversity.R")

vacc_data <- vacc_load_data() %>% filter(country == "Denmark")
div_data <- div_load_data("../temp/DNK/diversity_by_time.csv")
merged_data <- div_data %>%
    full_join(vacc_data, by = c("date" = "date"))
```


## Basic plots

### Diversity over time

```{r}
ggplot(div_data) +
        geom_point(aes(x = date, y = diversity_measure))
```


### Vaccination over time

```{r}
vacc_full_data <- vacc_load_data()
ggplot(vacc_full_data) +
  geom_line(aes(x = date, y = people_vaccinated_per_hundred, color = country), size=1) +
  scale_y_continuous(
          name = "Viccination per hundred people (at least one dosis)",
  ) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), text = element_text(size=20))
```


## Diversity vs. Vaccination

```{r}
ggplot(merged_data, aes(x = date)) +
  geom_point(aes(y = diversity_measure)) +
  geom_line(aes(y = people_vaccinated_per_hundred)) +
  scale_y_continuous(
    name = "Diversity (points)",
    sec.axis = sec_axis(~.*1, name="Vaccination per hundred people (line)")
  ) +
  theme_bw()
```
